brute force understanding the ground truth

In [2]:
import plotly.express as px
import numpy as np
from tqdm import tqdm
from updated_run import run_simulation

In [ ]:
data = np.array([[0, 0, 0]])
for i in tqdm(range(0, 10)):
    # calculate neuron firing rate for random params
    amp = np.random.uniform(0, 5)
    pw = np.random.uniform(0, 80)
    print("Testing ", (amp, pw))
    res = run_simulation(amp, pw)
    # store results
    data = np.vstack((data, [amp, pw, res]))
    if i%100 == 99:
        np.save('groundtruth.npy', data)
    # show results
    if i%5 == 4:
        plt = px.scatter(x=data[:, 0], y=data[:, 1], color=data[:, 2])
        plt.show()

  0%|          | 0/10 [00:00<?, ?it/s]

Testing  (3.4822877957551563, 59.643642853168195)
[[ 0.          0.          0.        ]
 [ 3.4822878  59.64364285 48.13873229]]


Testing  (4.81860285326672, 47.364210188313436)
Testing  (3.869864460669092, 4.4131867682419035)
Testing  (2.859021919965647, 25.01810675306362)
Testing  (4.255149341464369, 0.07146934458376997)
Testing  (3.914843671808451, 68.31647121705446)
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.48228780e+00 5.96436429e+01 4.81387323e+01]
 [4.81860285e+00 4.73642102e+01 6.67164704e+01]
 [3.86986446e+00 4.41318677e+00 3.99920239e+01]
 [2.85902192e+00 2.50181068e+01 4.77144274e+01]
 [4.25514934e+00 7.14693446e-02 7.97167490e+01]
 [3.91484367e+00 6.83164712e+01 5.60946929e+01]]


100%|██████████| 10/10 [00:00<00:00, 67.73it/s]

Testing  (1.2817035371085594, 10.946267628190052)
Testing  (1.6952862976727472, 79.44869484525361)
Testing  (4.1936700156373385, 1.1098781351717335)
Testing  (2.5477142554037986, 77.07436303743707)
